# Generated by Django 5.1.5 on 2025-09-19 18:02

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('ar', 'Arabe'), ('fr', 'Français')], default='fr', max_length=100)),
                ('titre_document', models.CharField(max_length=100)),
                ('titre_piece_join', models.CharField(max_length=100)),
                ('piece_join', models.FileField(upload_to='pieces_jointes/avis_infos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvisInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_offre', models.CharField(choices=[('OFFRE_EMPLOI', "Offre d'emploi"), ('consultants', 'Consultants')], default='OFFRE_EMPLOI', max_length=100)),
                ('titre', django_ckeditor_5.fields.CKEditor5Field(verbose_name='titre')),
                ('titre_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='titre_ar')),
                ('titre_documents_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='titre_documents_ar')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('description_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description_ar')),
                ('message_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='message_ar')),
                ('date_mise_en_ligne', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_limite', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('lieu_ar', models.CharField(default='غير محدد', max_length=100)),
                ('nombre_vu', models.IntegerField(default=0)),
                ('si_archiver', models.BooleanField(default=False)),
                ('si_valider', models.BooleanField(default=False)),
                ('si_groupement', models.BooleanField(default=False)),
                ('si_fixe', models.BooleanField(default=False)),
                ('si_traduire', models.BooleanField(default=False)),
                ('acee_traduction', models.BooleanField(default=False)),
                ('titre_entreprise', models.CharField(blank=True, max_length=100, null=True)),
                ('titre_entreprise_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('lien', models.URLField(blank=True, null=True)),
                ('groupement_spacial', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=100)),
                ('titre_groupement_cpacial', models.CharField(blank=True, max_length=100, null=True)),
                ('titre_groupement_cpacial_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('si_principal', models.BooleanField(default=False, verbose_name="Est l'avis principale")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('a_traduire', models.BooleanField(default=False, verbose_name='pres a traduire')),
                ('avis_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_liees', to='avis_infos.avisinfos', verbose_name="Rattachée à l'avis")),
            ],
            options={
                'verbose_name': 'Avi Info',
                'verbose_name_plural': 'Avis Infos',
                'permissions': [('grouper_avisinfos', 'Peut grouper des avis/infos'), ('valider_avisinfos', 'Peut valider un avis/infos'), ('fixe_avisinfos', 'Peut fixe un avis/infos'), ('traduire_avisinfos', 'Peut traduire un avis/infos')],
            },
        ),
    ]
