# Generated by Django 5.1.5 on 2025-09-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis_infos', '0003_avisinfos_afficher_heures_and_more'),
        ('avis_infos', '0003_avisinfos_si_valider_ar'),
    ]

    operations = [
    ]
