# Generated by Django 5.1.5 on 2025-09-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avis_infos', '0004_merge_20250927_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisinfos',
            options={'permissions': [('grouper_avisinfos', 'Peut grouper des avis/infos'), ('valider_avisinfos', 'Peut valider un avis/infos FR'), ('valider_ar_avisinfos', 'Peut valider un avis/infos AR'), ('change_categorie_avisinfos', 'Peut change categorie un avis/infos'), ('fixe_avisinfos', 'Peut fixe un avis/infos'), ('traduire_avisinfos', 'Peut traduire un avis/infos')], 'verbose_name': 'Avi Info', 'verbose_name_plural': 'Avis Infos'},
        ),
    ]
