# Generated by Django 5.1.5 on 2025-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis_infos', '0005_alter_avisinfos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisinfos',
            name='avis_fixe',
            field=models.BooleanField(default=False, verbose_name='Avis fixé'),
        ),
    ]
