# Generated by Django 5.1.5 on 2025-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(help_text='Ex: Licence en informatique', max_length=255, verbose_name='Nom du diplôme')),
                ('etablissement', models.CharField(help_text='Ex: Université de Nouakchott', max_length=255, verbose_name='Établissement')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
        ),
    ]
