# Generated by Django 5.1.5 on 2025-09-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diplomes', '0001_initial'),
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplome',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='gestion_utilisateur.candidat', verbose_name='Candidat'),
        ),
    ]
