"""
Django settings for beta project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from .ckeditorConfig import *
# import dj_database_url
# import environ
# env = environ.Env()
# environ.Env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



LANGUAGE_CODE = 'fr'

USE_L10N = True
USE_TZ = True
TIME_ZONE = 'UTC'
USE_I18N = True
SECRET_KEY = 'django-insecure-vin@n5=b!85%nbp=+%w_+qk1phu!7y2fg#+$mlwh2y4og0qt$&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



AUTH_USER_GROUPS_RELATED_NAME = 'utilisateur_personnalise_groups'
AUTH_USER_USER_PERMISSIONS_RELATED_NAME = 'utilisateur_personnalise_user_permissions'

# UPDATE gestion_utilisateur_utilisateurpersonnalise SET valide = 0 WHERE valide = 1;


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND ='django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'selmatesttestselma@gmail.com'
# EMAIL_HOST_USER ='permisiscae@gmail.com'
# EMAIL_HOST_PASSWORD = 'reyggfsmnfnvtesm'
EMAIL_HOST_USER ='betamessagerie@gmail.com'
EMAIL_HOST_PASSWORD = 'htnzjmcsoxzruxxe'

# settings.py

# Définir la durée de vie de la session à 5 minutes (5 * 60 secondes = 300 secondes)
SESSION_COOKIE_AGE = 30000000000

# S'assurer que la session expire lorsque le navigateur est fermé
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Mettre à jour la session à chaque requête pour réinitialiser le compteur d'inactivité
SESSION_SAVE_EVERY_REQUEST = True
# EMAIL_HOST_USER ='permisiscae@gmail.com'
# EMAIL_HOST_PASSWORD = 'reyggfsmnfnvtesm'


ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'django_ckeditor_5',
    'rest_framework',
    'corsheaders',
    'offres_emploi',
    'appels_offres',
    'avis_infos',
    'rest_framework.authtoken',
    'diplomes',
    'langues',
    'experience',
    'specialisation',
    'gestion_utilisateur',
    'contact',
    'temoignages',
     'captcha',
     'parametres',
     


]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',  # Barre d'outils complète
        'height': 300,  # Hauteur de l'éditeur
        'width': '100%',  # Largeur de l'éditeur
    },
}

# CKEDITOR_5_CONFIGS = {
#     'default': {
#         'toolbar': [
#             'bold', 'italic', 'underline', 'strikethrough', '|',
#             'fontSize', 'fontColor', 'fontBackgroundColor', '|',
#             'alignment', '|',
#             'bulletedList', 'numberedList', '|',
#             'link', 'imageUpload', '|',
#             'undo', 'redo',
#         ],
#     },
#     'extends': {
#         'toolbar': [
#             'bold', 'italic', 'underline', 'strikethrough', '|',
#             'fontSize', 'fontColor', 'fontBackgroundColor', '|',
#             'alignment', '|',
#             'bulletedList', 'numberedList', '|',
#             'link', 'imageUpload', '|',
#             'undo', 'redo',
#         ],
#     },
# }

MIDDLEWARE = [
     'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
    'appels_offres.middleware.ArchiveExpiredOffersMiddleware',
    
]

CORS_ALLOW_ALL_ORIGINS = True 


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]


# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]


# CORS_ALLOW_HEADERS = [
#     "content-type",
#     "X-CSRFToken",
# ]

ROOT_URLCONF = 'beta.urls'

SESSION_ENGINE = "django.contrib.sessions.backends.db"

SESSION_COOKIE_SAMESITE = 'Lax'  # ou 'None' si HTTPS et cross-site, attention
SESSION_COOKIE_SECURE = False    # à True si HTTPS

CSRF_COOKIE_SAMESITE = 'Lax'    # idem



# URL pour accéder aux fichiers multimédias
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'beta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',  # Moteur de base de données
#         'NAME': 'new_beta_dep',   # Nom de la base de données
#         'USER': 'root',       # Nom d'utilisateur MySQL
#         'PASSWOR': '',      # Mot de passe MySQL
#         'HOST': 'localhost',                   # Hôte (généralement 'localhost')
#         'PORT': '3306',                        # Port MySQL (par défaut 3306)
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4',
#         },
#     }
# }

# DATABASES = {
#     'default': dj_database_url.config(default=env("DATABASE_URL"))
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/






# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'gestion_utilisateur.UtilisateurPersonnalise'
# AUTH_USER_MODEL = 'offres_emploi.UtilisateurPersonnalise'
LOGIN_URL = '/connexion/'

