# Generated by Django 5.1.5 on 2025-09-19 18:02

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', django_ckeditor_5.fields.CKEditor5Field(verbose_name='titre')),
                ('titre_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='titre_ar')),
                ('titre_documents_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='titre_documents_ar')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('description_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description_ar')),
                ('message_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='message_ar')),
                ('type_offre', models.CharField(choices=[('OFFRE_EMPLOI', "Offre d'emploi"), ('consultants', 'Consultants')], default='OFFRE_EMPLOI', max_length=100)),
                ('date_mise_en_ligne', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_limite', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('lieu_ar', models.CharField(blank=True, default='غير محدد', max_length=255, null=True)),
                ('nombre_vu', models.IntegerField(default=0)),
                ('si_national', models.BooleanField(default=True)),
                ('si_archiver', models.BooleanField(default=False)),
                ('si_valider', models.BooleanField(default=False)),
                ('si_groupement', models.BooleanField(default=False)),
                ('si_fixe', models.BooleanField(default=False)),
                ('si_traduire', models.BooleanField(default=False)),
                ('acee_traduction', models.BooleanField(default=False)),
                ('titre_entreprise', models.CharField(blank=True, max_length=100, null=True)),
                ('titre_entreprise_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(choices=[('standard', 'Standard'), ('autre', 'Autre')], default='standard', max_length=100)),
                ('groupement_spacial', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=100)),
                ('titre_groupement_cpacial', models.CharField(blank=True, max_length=100, null=True)),
                ('titre_groupement_cpacial_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('si_principal', models.BooleanField(default=False, verbose_name="Est l'offre principale")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('afficher_heures', models.BooleanField(default=True, verbose_name='Afficher les heures avec la date')),
                ('a_traduire', models.BooleanField(default=False, verbose_name='pres a traduire')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_emploi', to='gestion_utilisateur.client')),
                ('offre_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_liees', to='offres_emploi.offreemploi', verbose_name="Rattachée à l'offre")),
                ('valider_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_emploi_valider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emplois",
                'permissions': [('grouper_offreemploi', "Peut grouper des offres d'emploi"), ('valider_offreemploi', "Peut valider un offre d'emploi"), ('fixe_offreemploi', "Peut fixe un offre d'emploi"), ('traduire_offreemploi', "Peut traduire un offre d'emploi"), ('porte_feuille', 'Peut consulter porte feuille')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('ar', 'Arabe'), ('fr', 'Français')], default='fr', max_length=100)),
                ('titre_document', models.CharField(max_length=100)),
                ('titre_piece_join', models.CharField(max_length=100)),
                ('piece_join', models.FileField(upload_to='pieces_jointes/offres_emploi')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('offre_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='offres_emploi.offreemploi')),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('type_publicite', models.CharField(choices=[('GENERAL', 'Général'), ('OFFRES', 'Publicité des offres'), ('AVIS', 'Publicité des avis'), ('APPELS', "Publicité des appels d'offre"), ('COTE', 'Publicité à côté')], default='GENERAL', max_length=20, verbose_name='Type de publicité')),
                ('type_contenu', models.CharField(choices=[('LIEN', 'Lien'), ('DOCUMENT', 'Document')], default='LIEN', max_length=10, verbose_name='Type')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='publicites/document', verbose_name='Document')),
                ('image', models.FileField(blank=True, null=True, upload_to='publicites/images/')),
                ('date_limite', models.DateField(verbose_name='Date limite')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_utilisateur.client', verbose_name='ID du client')),
            ],
        ),
    ]
