# Generated by Django 5.1.5 on 2025-09-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_emploi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='si_valider_ar',
            field=models.BooleanField(default=False),
        ),
    ]
