# Generated by Django 5.1.5 on 2025-09-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_emploi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='date_mise_en_ligne',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise en ligne'),
        ),
    ]
