# Generated by Django 5.1.5 on 2025-09-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres_emploi', '0002_alter_offreemploi_date_mise_en_ligne'),
        ('offres_emploi', '0002_offreemploi_si_valider_ar'),
    ]

    operations = [
    ]
