# Generated by Django 5.1.5 on 2025-09-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres_emploi', '0003_merge_20250927_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offreemploi',
            options={'permissions': [('grouper_offreemploi', "Peut grouper des offres d'emploi"), ('valider_offreemploi', "Peut valider un offre d'emploi FR"), ('valider_ar_offreemploi', "Peut valider un offre d'emploi AR"), ('change_categorie_offreemploi', "Peut change categorie un offre d'emploi"), ('fixe_offreemploi', "Peut fixe un offre d'emploi"), ('traduire_offreemploi', "Peut traduire un offre d'emploi"), ('porte_feuille', 'Peut consulter porte feuille')], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emplois"},
        ),
    ]
