# Generated by Django 5.1.5 on 2025-09-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_emploi', '0004_alter_offreemploi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='titre_document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
