# Generated by Django 5.1.5 on 2025-10-02 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres_emploi', '0005_alter_document_titre_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='titre_document',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
