# Generated by Django 5.1.5 on 2025-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('poste', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
