# Generated by Django 5.1.5 on 2025-09-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience', '0001_initial'),
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='gestion_utilisateur.candidat'),
        ),
    ]
