# Generated by Django 5.1.5 on 2025-09-19 18:02

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', django_ckeditor_5.fields.CKEditor5Field(verbose_name='titre')),
                ('titre_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='titre_ar')),
                ('titre_entreprise', models.CharField(blank=True, max_length=100, null=True)),
                ('titre_entreprise_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('titre_documents_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='titre_documents_ar')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('description_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description_ar')),
                ('message_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='message_ar')),
                ('type_offre', models.CharField(choices=[('OFFRE_EMPLOI', "Offre d'emploi"), ('APPEL_OFFRE', "Appel d'offre")], default='APPEL_OFFRE', max_length=100)),
                ('type_s', models.CharField(choices=[('internationaux', 'Internationaux'), ('consultations', 'Consultations'), ('locaux', 'Locaux'), ('manifestations', "Manifestations d'Intérêts")], default='internationaux', max_length=100)),
                ('date_mise_en_ligne', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_limite', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('lieu_ar', models.CharField(default='غير محدد', max_length=100)),
                ('nombre_vu', models.IntegerField(default=0)),
                ('si_archiver', models.BooleanField(default=False)),
                ('si_valider', models.BooleanField(default=False)),
                ('si_groupement', models.BooleanField(default=False)),
                ('si_fixe', models.BooleanField(default=False)),
                ('si_traduire', models.BooleanField(default=False)),
                ('acee_traduction', models.BooleanField(default=False)),
                ('groupement_spacial', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=100)),
                ('si_principal', models.BooleanField(default=False, verbose_name="Est l'offre principale")),
                ('titre_groupement_cpacial', models.CharField(blank=True, max_length=100, null=True)),
                ('titre_groupement_cpacial_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('a_traduire', models.BooleanField(default=False, verbose_name='pres a traduire')),
            ],
            options={
                'verbose_name': "Appel d'offre",
                'verbose_name_plural': "Appels d'offres",
                'permissions': [('grouper_appeloffre', "Peut grouper des appel d'offre"), ('valider_appeloffre', "Peut valider un appel d'offre"), ('fixe_appeloffre', "Peut fixe un appel d'offre"), ('traduire_appeloffre', "Peut traduire un appel d'offre")],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(choices=[('ar', 'Arabe'), ('fr', 'Français')], default='fr', max_length=100)),
                ('titre_document', models.CharField(max_length=100)),
                ('titre_piece_join', models.CharField(max_length=100)),
                ('piece_join', models.FileField(upload_to='pieces_jointes/appels_offres/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
