# Generated by Django 5.1.5 on 2025-09-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appels_offres', '0001_initial'),
        ('gestion_utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_offres', to='gestion_utilisateur.client'),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='offre_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_liees', to='appels_offres.appeloffre', verbose_name="Rattachée à l'offre"),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='valider_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offres_valider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='appels_offres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appels_offres.appeloffre'),
        ),
    ]
