# Generated by Django 4.2.4 on 2025-09-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='afficher_heures',
            field=models.BooleanField(default=True, verbose_name='Afficher les heures avec la date'),
        ),
    ]
