# Generated by Django 5.1.5 on 2025-09-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0003_appeloffre_afficher_heures'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='si_valider_ar',
            field=models.BooleanField(default=False),
        ),
    ]
