# Generated by Django 5.1.5 on 2025-09-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0003_appeloffre_afficher_heures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='date_mise_en_ligne',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise en ligne'),
        ),
    ]
