# Generated by Django 5.1.5 on 2025-09-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0004_alter_appeloffre_date_mise_en_ligne'),
        ('appels_offres', '0004_appeloffre_si_valider_ar'),
    ]

    operations = [
    ]
