# Generated by Django 5.1.5 on 2025-09-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0005_merge_20250927_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'permissions': [('grouper_appeloffre', "Peut grouper des appel d'offre"), ('valider_appeloffre', "Peut valider un appel d'offre FR"), ('valider_ar_appeloffre', "Peut valider un appel d'offre AR"), ('change_categorie_appeloffre', "Peut change categorie un appel d'offre"), ('fixe_appeloffre', "Peut fixe un appel d'offre"), ('traduire_appeloffre', "Peut traduire un appel d'offre")], 'verbose_name': "Appel d'offre", 'verbose_name_plural': "Appels d'offres"},
        ),
    ]
