# Generated by Django 5.1.5 on 2025-10-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0006_alter_appeloffre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='lieu',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='lieu_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
