# Generated by Django 5.1.5 on 2025-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0007_alter_appeloffre_lieu_alter_appeloffre_lieu_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='lieu_ar',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
