# Generated by Django 5.1.5 on 2025-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreoffres', models.PositiveIntegerField(default=0, verbose_name="Nombre d'offres")),
                ('nombreapples', models.PositiveIntegerField(default=0, verbose_name="Nombre d'appels d'offre")),
                ('nombreavis', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('nombreoffresAr', models.PositiveIntegerField(default=0, verbose_name='عدد الوظائف')),
                ('nombreapplesAr', models.PositiveIntegerField(default=0, verbose_name='عدد طلبات العروض')),
                ('nombreavisAr', models.PositiveIntegerField(default=0, verbose_name='عدد الإشعارات')),
            ],
        ),
    ]
